### ISSUE TITLE
The requested image's platform not match

### ISSUE THREAD

**Issue by jiatao99** [jlesage/docker-nginx-proxy-manager#268] opened 2022-10-28 17:43 UTC
Try to use your docker image, and got the following error:

the requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8). I am using Ubuntu 22.04

any idea how to fix it?

Another question, after I use the web interface to grab a Let's encrypt certificate, where does it saved? I use the following docker compose:

```yaml
version: '3'
services:
  nginx-proxy-manager:
    image: jlesage/nginx-proxy-manager
    container_name: nginx
    ports:
      - "8181:8181"
      - "8080:8080"
      - "4443:4443"
    volumes:
      - /docker/appdata/nginx:/config:rw
```

Thanks

**Comment by jlesage** [comment] 2023-03-05 21:48
> the requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8)

This was caused by the fact that image was not supporting arm.  You should no longer have this issue with the latest version.

> Another question, after I use the web interface to grab a Let's encrypt certificate, where does it saved?

According to your compose file, everything is saved under `/docker/appdata/nginx`.

**Comment by jlesage** [comment] 2023-03-05 21:48
Closing this issue.  Please re-open if needed.

**Closed by jlesage** 2023-03-05 21:48 UTC
